---
- hosts: all
  tasks:
    - name: install apache 
      yum:
        name: httpd 

    - name: enable apache
      systemd:
        name: httpd
        state: started

    - name: stop firewall
      systemd: 
        name: firewalld
        state: stopped
